### PR TITLE
feat: created core-app ingress

### LINKED ISSUE #48: Create k8s ingress to make core app accessible from outside of the cluster

### PR DESCRIPTION
**Pull request by Oleksandr6676**
It creates core-app ingress

Closes #48

### CODE REVIEW

**Comment by Oleksandr6676** [comment]
Hi @JanMate! I have a small question. I verified, this ingress works fine through minikube ssh, so I can normally send requests to our /health endpoint via curl command. But it is not accessible through browser, is it expected behaviour?

**Comment by JanMate** [comment]
> Hi @JanMate! I have a small question. I verified, this ingress works fine through minikube ssh, so I can normally send requests to our /health endpoint via curl command. But it is not accessible through browser, is it expected behaviour?

1) Please, describe your steps how did you set it and verified it - real examples (code snippets) are really appreciated.

2) Check this out https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/ and try to clarify what the problem was and what it helped to solve the issue.

**Review by JanMate — CHANGES_REQUESTED** [review]
Anyway, it looks good to me, so when I have time, I'll check it in more detailed way on my minikube. Until that time, please, try to make it accessible from your native OS.

**Comment by JanMate** [comment]
Verified on kubernetes 1.18 and works properly. The issue was really a missing row in the routing table.

When you verify it as well and fix the host name, then we can merge.

**Review by JanMate — APPROVED** [review]

**Pull request merged**
